### PR TITLE
Use contiguous block storage

### LINKED ISSUE #14: Use storage of numerical values similar to Tpetra and TPLs
Store each block contiguously in a row-major fashion

If the block (row, col) is of interest, the numerical values will be in the range {values[row_map[row]], ..., values[row_map[row] + bs*bs - 1]}   (where bs is the block size).

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Closes #14

### CODE REVIEW

**Comment by fnrizzi** [comment]
@uhetmaniuk just getting to this. I see lots of code changed. So basically this is a refactor to store each block with row-major layout?

**Comment by uhetmaniuk** [comment]
@fnrizzi Yes it is mostly a refactor for working with a block storage (where each block is stored contiguously in a row-major fashion). 
I have also added the structure BSPMV_Functor and the function bspmv_raw_[*] to mimic the CrsMatrix implementation for the "raw" OpenMP and the fallback GPU case.

**Comment by uhetmaniuk** [comment]
@fnrizzi @MikolajZuzek 
Can I merge this PR ?

**Comment by fnrizzi** [comment]
sounds good to me!

**Pull request merged**
